import type { ProjectContentBlock } from "./types";

export const canberrarepContent: ProjectContentBlock[] = [
  { type: "heading", level: 2, text: "Overview" },
  {
    type: "paragraph",
    text: "Canberra REP is Australia's oldest community theatre. The site covers seasons and production content, with ticketing handled by an external booking system.",
  },
  {
    type: "paragraph",
    text: "I delivered the design and development end to end, including the migration off Drupal 7, the design system, and accessibility compliance. One constraint shaped the project from the outset: the client's content team has no technical background, so after handover every routine update had to be possible from the dashboard alone, without opening a single page template. That constraint determined how the content was structured and where the styles lived, and it determined where the two technical problems below could be solved.",
  },
  { type: "heading", level: 2, text: "Challenges" },
  { type: "heading", level: 3, text: "Editable content within a locked layout" },
  {
    type: "paragraph",
    text: "The client needed to maintain the site independently, but handing over edit access to the page builder would have handed over the ability to break the layout along with it.",
  },
  {
    type: "paragraph",
    text: "My first thought was to lock down individual builder controls through a permissions plugin. I ruled it out fairly quickly. Control level locking is a blacklist approach: every builder release can introduce new controls, so the maintenance cost keeps accruing, and it still doesn't stop someone dragging a nested container out of place. I went with a whitelist instead. Layout belongs to the template, content belongs to the fields. Each content type got its own template, with the grid, the typographic hierarchy, and the component structure fixed at the template layer. Everything variable is exposed through ACF field groups, so what the editor meets in the dashboard is a form, not a canvas.",
  },
  {
    type: "paragraph",
    text: "Field types do the validation work here. An image field rejects anything that isn't an image, a date field rejects free text, a repeater enforces a consistent shape across entries. Most content errors are caught by the structure at the point of input, which means the templates don't need defensive logic. Styles are consolidated into the global design system and the child theme stylesheet: anything that applies to more than one element belongs to the design system, and writing it into a single widget is just deferred maintenance.",
  },
  {
    type: "paragraph",
    text: "One snag in implementation. The loop component's underlying query returns published content only, so draft productions came back as an empty result set and the client couldn't check the layout before publishing. I opened up the status restriction through a query filter hook and scoped it to preview requests, which leaves the public query behaviour untouched and keeps drafts out of public listings.",
  },
  {
    type: "heading",
    level: 3,
    text: "Accessibility on DOM generated by third parties",
  },
  {
    type: "paragraph",
    text: "The HTML at the template layer was entirely under my control. The compliance gaps traced back to a single source: some of the DOM wasn't written by us. The loop component's container structure is produced by the page builder at render time, and the footer navigation's hierarchy markup is produced by the menu plugin in the browser. The builder's custom attributes only reach the widget's outermost wrapper, so they can't touch the container nodes generated inside it.",
  },
  {
    type: "paragraph",
    text: "There's no single entry point for this, so I worked back from when each piece of DOM comes into existence and intervened at the matching layer. Structure that's settled before render was fixed in the template: the full page template bypasses the semantic skeleton the theme normally outputs, so changing the outermost container's tag to main restored the landmark, and the ARIA parent and child relationship issues were pushed down to the loop item template. Nodes written at runtime give the server no point of entry, so a MutationObserver watches for them and corrects focus reachability and heading levels once the markup lands. The homepage runs a rotating banner and has no stable top level heading, so I injected a visually hidden H1 server side and scoped it to the front page so it doesn't affect the heading structure of any other template.",
  },
  {
    type: "paragraph",
    text: "Hidden elements use the visually hidden pattern rather than display: none. The latter removes the node from the accessibility tree altogether, which makes it non existent as far as a screen reader is concerned, and these are precisely the elements that need to be read but not seen.",
  },
  {
    type: "paragraph",
    text: "Patching at runtime isn't the cleanest architectural answer. The cleaner one would have been to pull the footer navigation into the template and render the markup myself, but that would have cost the client the ability to manage navigation from the native menus screen, which cuts against the whole point of the handover. It's a trade off between architectural cleanliness and client autonomy, and it's documented as such in the handover notes.",
  },
  { type: "heading", level: 2, text: "Outcome" },
  {
    type: "paragraph",
    text: "Every accessibility issue raised in the audit has been resolved and the structured data validates. Machine readable output never passes in front of a human eye and won't flag itself when it breaks, so the migration checklist treats it as a verification step in its own right. I designed and delivered two training sessions for the client's editors and administrator, with supporting documentation. Since handover, season updates, production listings, page adjustments, and form management are all handled by the client's team without developer involvement, and the modular content structure means new content types can be added without touching existing templates.",
  },
];
